# Generated by Django 6.0.5 on 2026-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_epi', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
