# Generated by Django 6.0.5 on 2026-06-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('FORNECIDO', 'Fornecido'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='EMPRESTADO', max_length=20),
        ),
    ]
